Data model
EternalDeiwos/logi-bot pull request #1
Opened 2024-07-14 21:13 UTC by P0etC

Just ran linter and  added tables to the db

2024-07-19 14:25 UTC, EternalDeiwos requested changes
Take a look at comments and let me know what you think @P0etC

2024-07-19 14:25 UTC, EternalDeiwos commented on supabase/migrations/20240714205505_first_tables.sql
> +create table "public"."location" (
Lets add some QoL here:

- `iso2` - 2 character abbreviation for location, nullable
- `iso3` - 3 character abbreviation for location, nullable
- `slang` - `text[]`, default `[]`, additional terms used to describe a location that do not directly relate to their actual name. e.g. Cpass = Calahan's Passage.

2024-07-19 14:25 UTC, EternalDeiwos commented on supabase/migrations/20240714205505_first_tables.sql
> +create table "public"."stockpile" (
We need to add something to track which war a stockpile belongs to. I would like to do a separate table, so that we can track war start and war end as well, so that we can easily work out what is the current war.

2024-07-19 14:25 UTC, EternalDeiwos commented on supabase/migrations/20240714205505_first_tables.sql
> +    "code" text not null,
This should be nullable, or default to `000000`. I want to ignore this column until we actually plan to use it. Or we could just omit the column entirely.

2024-07-19 14:25 UTC, EternalDeiwos commented on supabase/migrations/20240714205505_first_tables.sql
> +    "crated" boolean not null
This should be an integer. We'll keep two counts per row.

2024-07-19 14:25 UTC, EternalDeiwos commented on supabase/migrations/20240714205505_first_tables.sql
> +grant delete on table "public"."items" to "authenticated";
Remove any privileges from all roles except `service_role`. The bot will be using that role. We can add more later if necessary.

2024-08-05 18:02 UTC, P0etC commented on supabase/migrations/20240714205505_first_tables.sql
> +create table "public"."location" (
Done

2024-08-05 18:03 UTC, P0etC commented on supabase/migrations/20240714205505_first_tables.sql
> +create table "public"."stockpile" (
You  think it  should there should be like a war table with war start and war end?

2024-08-05 18:04 UTC, P0etC commented on supabase/migrations/20240714205505_first_tables.sql
> +    "code" text not null,
Done

2024-08-05 18:04 UTC, P0etC commented on supabase/migrations/20240714205505_first_tables.sql
> +    "crated" boolean not null
Done

2024-08-05 18:05 UTC, P0etC commented on supabase/migrations/20240714205505_first_tables.sql
> +grant delete on table "public"."items" to "authenticated";
I looked into the docs and tried to find a place where I can do it but really cant find a place to change roles on mass most of the roles are even protected from  me  and I cant change them.

2024-08-05 18:19 UTC, P0etC commented on supabase/migrations/20240714205505_first_tables.sql
> +grant delete on table "public"."items" to "authenticated";
Added war table  like it was proposed in the last discord schema  and added war number to stockpile table

2024-08-05 19:29 UTC, P0etC commented
I got inspired by your pr and now i dont use the auto migration tool and created  migration files for every table seperatly. This shouuld also  help   with review. @EternalDeiwos would be great if you could take  a look at it.

2024-08-09 09:00 UTC, EternalDeiwos commented on supabase/migrations/20240805185042_stockpiles.sql
> +create table "public"."stockpile" (
Inconsistent capitalization on SQL keywords. Lets make all keywords upper case.

2024-08-09 09:01 UTC, EternalDeiwos commented on supabase/migrations/20240805185042_stockpiles.sql
> +    "location_id" bigint not null,
Lets make this column `poi_id` to match new naming.

2024-08-09 09:02 UTC, EternalDeiwos commented on supabase/migrations/20240805185042_stockpiles.sql
> +    "role_sf" bigint not null,
Drop this column to match new design

2024-08-09 09:07 UTC, EternalDeiwos requested changes
Some small changes requested inline. 

Major change is related to the `items` table — I've put together a PR #4 with a `catalog` table which includes logic to import the JSON file and a view that provides appropriate access to the fields. You'll need to review that and adjust this PR to replace the `items` table.

2024-08-10 09:34 UTC, EternalDeiwos commented
Oh and also we need to use `_` instead of `-` in table names because postgres does not like `-`.

2024-08-15 09:37 UTC, EternalDeiwos commented
In the interest of moving forward, I've implemented this with #5.

2024-08-15 09:37 UTC, closed without merging